modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile = "icon.png"
description='''
${mod_description}
'''

[[mixins]]
config="nea_emf_compat.mixins.json"

[[dependencies.nea_emf_compat]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.nea_emf_compat]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.nea_emf_compat]]
modId="notenoughanimations"
mandatory=true
versionRange="[1.8,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.nea_emf_compat]]
modId="entity_model_features"
mandatory=true
versionRange="[3.2.4,)"
ordering="AFTER"
side="CLIENT"
